version: "3"

networks:
  directus:
    
services:
  #
  # Load balancer to accept requests from app and app on port 80
  # based on the requested hostname
  #
  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - directus

  #
  # Database
  #
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "directus"
      MYSQL_USER: "directus"
      MYSQL_PASSWORD: "directus"
      MYSQL_ROOT_PASSWORD: "directus"
    ports:
      - 3306:3306    
    networks:
      - directus

  #
  # Directus instance.
  # This should serve directus and won't work before database
  # is properly installed by running the installer.
  #
  directus:
    image: directus/directus:v8-apache
    environment:
      # Load balancer
      VIRTUAL_HOST: "directus.localtest.me"

      # App
      DIRECTUS_ENV: "production"

      # These are now required, make sure to always set
      # to something unique while in production
      DIRECTUS_AUTH_PUBLICKEY: "some random secret"
      DIRECTUS_AUTH_SECRETKEY: "another random secret"

      # Database
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "directus"
      DIRECTUS_DATABASE_PASSWORD: "directus"

      #
      # These are highly recommended for proper cloud native
      # installations, but not in this example
      #
      # Storage
      #DIRECTUS_STORAGE_ADAPTER: "s3"
      #DIRECTUS_STORAGE_ROOT: "/images/"
      #DIRECTUS_STORAGE_ROOTURL: "http://cdn.localtest.me/images"
      #DIRECTUS_STORAGE_THUMBROOT: "/images/thumbs/"
      #DIRECTUS_STORAGE_KEY: "storage_key"
      #DIRECTUS_STORAGE_SECRET: "storage_secret"
      #DIRECTUS_STORAGE_REGION: "us-east-1"
      #DIRECTUS_STORAGE_BUCKET: "cdn.localtest.me"

    # Uploads gets saved in uploads folder
    volumes:
      - ./data/config:/var/directus/config
      - ./data/uploads:/var/directus/public/uploads
    
    networks:
      - directus